const test=require('node:test'),assert=require('node:assert/strict');
const {LiveSwitchService,ACCOUNT_PREFIX,QUOTA_REFRESH_PREFIX}=require('../out/live-switch');
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const token=(access,refresh='synthetic-refresh')=>JSON.stringify({auth_method:'consumer',token:{access_token:access,refresh_token:refresh,expiry:'2026-12-01T00:00:00Z'}});
function fixture(){const map=new Map(),calls=[];const old={keyring:null,file:token('synthetic-old'),keyringState:'unobserved'};const account={id,label:'Synthetic',expectedEmail:'synthetic@example.test',capturedAt:'2026-10-01T00:00:00Z',identitySource:'hub',hostId:'host-A',slots:old};map.set(ACCOUNT_PREFIX+id,JSON.stringify(account));map.set(ACCOUNT_PREFIX+other,'untouched-other-account');const vault={get:async k=>map.get(k),store:async(k,v)=>{calls.push(['store',k]);map.set(k,v)},delete:async k=>{calls.push(['delete',k]);map.delete(k)}};const service=new LiveSwitchService(vault,{read:async()=>{throw Error('must not access official slots')},write:async()=>{throw Error('must not modify official slots')}},'host-A');return{service,map,calls,vault,old,account,next:{...old,file:token('synthetic-new','synthetic-rotated-refresh')}};}
test('verified refreshed credentials replace only target encrypted copy and clear durable staging',async()=>{const f=fixture();const updated=await f.service.commitQuotaRefresh(id,f.old,f.next);assert.deepEqual(updated.slots,f.next);assert.deepEqual((await f.service.account(id)).slots,f.next);assert.equal(f.map.get(ACCOUNT_PREFIX+other),'untouched-other-account');assert.equal(f.map.has(QUOTA_REFRESH_PREFIX+id),false);assert.equal(f.calls[0][1],QUOTA_REFRESH_PREFIX+id);assert.equal(f.calls[1][1],ACCOUNT_PREFIX+id)});
test('changed snapshot or slot scope fails before staged write',async()=>{for(const next of [{...fixture().next,keyring:token('added-slot')},{...fixture().next,keyringState:undefined}]){const f=fixture();await assert.rejects(f.service.commitQuotaRefresh(id,f.old,next));assert.equal(f.calls.length,0)}const f=fixture();await assert.rejects(f.service.commitQuotaRefresh(id,{...f.old,file:token('wrong-old')},f.next),/REFRESH_CONFLICT/);assert.equal(f.calls.length,0)});
test('interrupted encrypted commit resumes idempotently from either side without restoring stale refresh',async()=>{for(const stage of ['account','cleanup']){const f=fixture();const store=f.vault.store,del=f.vault.delete;f.vault.store=async(k,v)=>{if(stage==='account'&&k===ACCOUNT_PREFIX+id)throw Error('synthetic failure');await store(k,v)};f.vault.delete=async k=>{if(stage==='cleanup')throw Error('synthetic failure');await del(k)};await assert.rejects(f.service.commitQuotaRefresh(id,f.old,f.next));assert.equal(f.map.has(QUOTA_REFRESH_PREFIX+id),true);f.vault.store=store;f.vault.delete=del;assert.deepEqual((await f.service.account(id)).slots,f.next);assert.equal(f.map.has(QUOTA_REFRESH_PREFIX+id),false);assert.equal(f.map.get(ACCOUNT_PREFIX+other),'untouched-other-account')}});
test('external replacement and foreign-host refresh staging never overwrite accounts',async()=>{const f=fixture();const after=JSON.stringify({...f.account,slots:f.next});f.map.set(QUOTA_REFRESH_PREFIX+id,JSON.stringify({schema:1,accountId:id,before:JSON.stringify(f.account),after}));const foreign=JSON.stringify({...f.account,label:'External'});f.map.set(ACCOUNT_PREFIX+id,foreign);await assert.rejects(f.service.account(id),/REFRESH_CONFLICT/);assert.equal(f.map.get(ACCOUNT_PREFIX+id),foreign);assert.equal(f.map.has(QUOTA_REFRESH_PREFIX+id),true);const g=fixture();const before={...g.account,hostId:'foreign'};g.map.set(QUOTA_REFRESH_PREFIX+id,JSON.stringify({schema:1,accountId:id,before:JSON.stringify(before),after:JSON.stringify({...before,slots:g.next})}));await assert.rejects(g.service.account(id),/HOST_ACCOUNT_MISMATCH/);assert.equal(g.calls.length,0)});
test('unverified staging bytes or identity metadata cannot change the selected record',async()=>{for(const changed of [{expectedEmail:'other@example.test'},{id:other},{slots:{keyring:null,file:'invalid'}}]){const f=fixture();f.map.set(QUOTA_REFRESH_PREFIX+id,JSON.stringify({schema:1,accountId:id,before:JSON.stringify(f.account),after:JSON.stringify({...f.account,...changed,slots:changed.slots||f.next})}));await assert.rejects(f.service.account(id),/RECOVERY_INVALID/);assert.equal(f.calls.length,0);assert.deepEqual(JSON.parse(f.map.get(ACCOUNT_PREFIX+id)),f.account)}});

test('quarantine preserves rotated material but account reads never promote it before server identity verification',async()=>{
 const {QUOTA_PENDING_PREFIX}=require('../out/live-switch'),f=fixture();await f.service.stageQuotaRefresh(id,f.old,f.next);
 assert.equal(f.map.has(QUOTA_PENDING_PREFIX+id),true);assert.deepEqual((await f.service.account(id)).slots,f.old);assert.deepEqual(await f.service.pendingQuotaRefresh(id,f.old),f.next);
 await f.service.commitQuotaRefresh(id,f.old,f.next);assert.deepEqual((await f.service.account(id)).slots,f.next);assert.equal(f.map.has(QUOTA_PENDING_PREFIX+id),false);
});
test('a changed account cannot consume another staged refresh candidate',async()=>{
 const f=fixture();await f.service.stageQuotaRefresh(id,f.old,f.next);f.map.set(ACCOUNT_PREFIX+id,JSON.stringify({...f.account,slots:{...f.old,file:token('external-access','external-refresh')}}));
 await assert.rejects(f.service.pendingQuotaRefresh(id,f.old),/REFRESH_CONFLICT/);assert.deepEqual((await f.service.account(id)).slots,{...f.old,file:token('external-access','external-refresh')});
});

test('different pending rotations cannot be silently overwritten but exact continuation is allowed',async()=>{
 const f=fixture();await f.service.stageQuotaRefresh(id,f.old,f.next);const replacement={...f.next,file:token('newer','rotated-again')};
 await assert.rejects(f.service.stageQuotaRefresh(id,f.old,replacement),/REFRESH_CONFLICT/);assert.deepEqual(await f.service.pendingQuotaRefresh(id,f.old),f.next);
 await f.service.stageQuotaRefresh(id,f.old,replacement,f.next);assert.deepEqual(await f.service.pendingQuotaRefresh(id,f.old),replacement);assert.deepEqual((await f.service.account(id)).slots,f.old);
});
