const test=require('node:test'),assert=require('node:assert/strict');const {wakeOccurrences,validateWakeSchedule,parseWakeCron}=require('../out/wake-schedule'),{WakeEngine}=require('../out/wake-engine'),{initialWakeState,parseWakeState}=require('../out/wake-state');
const A='11111111-1111-4111-8111-111111111111',T='22222222-2222-4222-8222-222222222222',R='33333333-3333-4333-8333-333333333333',NOW=Date.parse('2026-10-09T10:00:00Z');
const cron=(expression,timezone='Etc/UTC')=>({mode:'cron',timezone,times:[],weekdays:[],cron:expression});
const interval={mode:'interval',timezone:'Asia/Shanghai',times:[],weekdays:[],intervalMinutes:15,anchor:'2026-10-09T18:00:00+08:00'};
test('anchored intervals use elapsed time, shared preview, exact future boundaries and skip old intervals',()=>{assert.deepEqual(wakeOccurrences(interval,NOW,3),[NOW+900000,NOW+1800000,NOW+2700000]);assert.deepEqual(wakeOccurrences(interval,NOW-1,1),[NOW]);assert.equal(wakeOccurrences(interval,NOW+10*86400000+1000)[0],NOW+10*86400000+900000);assert.equal(validateWakeSchedule(interval).anchor,'2026-10-09T10:00:00.000Z');assert.throws(()=>validateWakeSchedule({...interval,intervalMinutes:0}),/INVALID/);assert.throws(()=>validateWakeSchedule({...interval,anchor:'bad'}),/INVALID/)});
test('five-field cron supports steps, lists, ranges, names and standard day OR weekday matching',()=>{assert.deepEqual(wakeOccurrences(cron('*/15 10-11 * OCT FRI'),NOW,5).map(t=>new Date(t).toISOString()),['2026-10-09T10:15:00.000Z','2026-10-09T10:30:00.000Z','2026-10-09T10:45:00.000Z','2026-10-09T11:00:00.000Z','2026-10-09T11:15:00.000Z']);assert.equal(new Date(wakeOccurrences(cron('0 8 15 * MON'),NOW)[0]).toISOString(),'2026-10-12T08:00:00.000Z');assert.equal(new Date(wakeOccurrences(cron('0 8 * * 7'),NOW)[0]).toISOString(),'2026-10-11T08:00:00.000Z');for(const expr of ['* * * *','0 24 * * *','*/0 * * * *','0 0 * JAN SUN-MON/0','0 0 * MON *','0 0 31 FEB *']){if(expr.includes('31 FEB'))assert.throws(()=>wakeOccurrences(cron(expr),NOW),/NO_OCCURRENCE/);else assert.throws(()=>parseWakeCron(expr),/INVALID/)}});
test('cron shares DST gap/repeated-hour behavior and previews annual/leap-year dates in the selected timezone',()=>{const after=Date.parse('2026-03-08T00:00:00Z');assert.equal(new Date(wakeOccurrences(cron('30 2 * * *','America/New_York'),after)[0]).toISOString(),'2026-03-09T06:30:00.000Z');const repeated=cron('30 1 * * *','America/New_York');assert.equal(new Date(wakeOccurrences(repeated,Date.parse('2026-11-01T05:31:00Z'))[0]).toISOString(),'2026-11-02T06:30:00.000Z');assert.deepEqual(wakeOccurrences(cron('0 0 29 FEB *'),NOW,5).map(t=>new Date(t).getUTCFullYear()),[2028,2032,2036,2040,2044]);assert.equal(new Date(wakeOccurrences(cron('0 8 * * *','Asia/Kathmandu'),NOW)[0]).toISOString(),'2026-10-10T02:15:00.000Z')});
function memory(){let state=initialWakeState(),tail=Promise.resolve();return{read:async()=>structuredClone(state),transaction(fn){const next=tail.then(()=>{const s=structuredClone(state),r=fn(s);state=parseWakeState(s);return r});tail=next.catch(()=>{});return next}}}
function fixture(schedule={mode:'quota-recovery',timezone:'Etc/UTC',times:[],weekdays:[],pollMinutes:15}){let now=NOW,fp='synthetic-bound',fraction=1,snapshotChange=s=>s,reads=0,calls=0,quotaHold,runHold;const store=memory(),execution={fingerprint:()=>fp,quota:async(task,signal)=>{reads++;if(quotaHold)await quotaHold(task,signal);return snapshotChange({accountId:A,modelId:'synthetic-text',endpoint:'daily',remainingFraction:fraction,queriedAt:new Date(now).toISOString(),resetAt:null})},run:async(_task,_signal,before)=>{if(runHold)await runHold();await before();calls++;return{phase:'succeeded',code:'WAKE_COMPLETE'}}},engine=new WakeEngine(store,execution,()=>{},()=>now);return{store,execution,engine,task:{id:T,revision:R,accountId:A,fingerprint:fp,modelId:'synthetic-text',endpoint:'daily',schedule,enabled:false,outputBudget:8,nextDue:0},setTime:t=>now=t,setFraction:f=>fraction=f,change:fn=>snapshotChange=fn,replace:()=>fp='changed',holdQuota:fn=>quotaHold=fn,holdRun:fn=>runHold=fn,get calls(){return calls},get reads(){return reads},get now(){return now}}}
const tick=()=>new Promise(setImmediate);
async function enabled(f){await f.engine.save(f.task);await f.engine.consent();await f.engine.pause(T,true);await f.engine.enable(true)}
async function next(f){f.setTime((await f.store.read()).tasks[0].nextDue);await f.engine.tick()}
test('full recovery is default off; first full baseline and 99.6% cannot send; exact fresh recovery sends once',async()=>{const f=fixture();await f.engine.save(f.task);f.setTime(NOW+900000);await f.engine.tick();assert.equal(f.reads,0);assert.equal(f.calls,0);await enabled(f);await next(f);assert.equal(f.calls,0);f.setFraction(.996);await next(f);assert.equal(f.calls,0);f.setFraction(1);await next(f);assert.equal(f.calls,1);await next(f);assert.equal(f.calls,1);assert.equal((await f.store.read()).tasks[0].recovery.fraction,1)});
test('unknown, wrong-model, stale and failed observations invalidate recovery without stamping a success time',async()=>{for(const change of [s=>({...s,remainingFraction:null}),s=>({...s,modelId:'another-model'}),s=>({...s,queriedAt:new Date(Date.parse(s.queriedAt)-60000).toISOString()}),()=>{throw Error('SYNTHETIC_FAILURE')}]){const f=fixture();await enabled(f);f.setFraction(.5);await next(f);const observed=(await f.store.read()).tasks[0].recovery.observedAt;f.change(change);await next(f);assert.equal(f.calls,0);assert.equal((await f.store.read()).tasks[0].recovery.observedAt,observed);assert.equal((await f.store.read()).tasks[0].recovery.valid,false);f.change(s=>s);f.setFraction(1);await next(f);assert.equal(f.calls,0);f.setFraction(.1);await next(f);f.setFraction(1);await next(f);assert.equal(f.calls,1)}});
test('two windows share a single metadata check and recovery request; edits, cancellation and replacement isolate late quota results',async()=>{for(const action of ['dedup','edit','cancel','replace','delete']){const f=fixture();await enabled(f);f.setFraction(.3);await next(f);f.setFraction(1);let resolve;f.holdQuota(()=>new Promise(r=>resolve=r));f.setTime((await f.store.read()).tasks[0].nextDue);const pending=f.engine.tick();while(!resolve)await tick();const other=new WakeEngine(f.store,f.execution,()=>{},()=>f.now);if(action==='dedup')await other.tick();if(action==='edit')await other.save({...f.task,enabled:true});if(action==='cancel')await other.cancel(T);if(action==='replace')f.replace();if(action==='delete')await other.remove(T);resolve();await pending;assert.equal(f.calls,action==='dedup'?1:0,action);assert.equal(f.reads,2);other.dispose()}});
test('missed recovery checks reset the baseline and never turn sleep into a catchup request',async()=>{const f=fixture();await enabled(f);f.setFraction(.2);await next(f);f.setFraction(1);f.setTime((await f.store.read()).tasks[0].nextDue+6*60000);await f.engine.tick();assert.equal(f.calls,0);assert.equal((await f.store.read()).tasks[0].recovery,undefined);await next(f);assert.equal(f.calls,0);assert.equal((await f.store.read()).instances.at(-2).code,'WAKE_TOO_LATE')});
test('recovery confirmation that expires during preparation prevents the durable sent marker and actual model request',async()=>{const f=fixture();await enabled(f);f.setFraction(.1);await next(f);f.setFraction(1);f.holdRun(async()=>f.setTime(f.now+60000));await next(f);assert.equal(f.calls,0);assert.equal((await f.store.read()).instances.at(-1).code,'WAKE_QUOTA_STALE');assert.equal((await f.store.read()).instances.at(-1).phase,'failed')});
test('interval and cron execution share preview times and skip missed runs without changing model/account/budget',async()=>{for(const schedule of [interval,cron('*/15 * * * *')]){const f=fixture(schedule);await enabled(f);const due=(await f.store.read()).tasks[0].nextDue;assert.equal(due,wakeOccurrences(schedule,NOW)[0]);await next(f);assert.equal(f.calls,1);f.setTime((await f.store.read()).tasks[0].nextDue+6*60000);await f.engine.tick();assert.equal(f.calls,1);assert.equal((await f.store.read()).instances.at(-1).phase,'skipped')}});
