const assert = require('node:assert/strict');
const vscode = require('vscode');
exports.run = async () => {
  console.log('Smoke checkpoint: test module entered');
  const extension = vscode.extensions.getExtension('xiaoxincodes.antigravity-account-manager');
  assert.ok(extension, 'Development extension must be discovered');
  const api = await extension.activate();
  console.log('Smoke checkpoint: extension activated');
  assert.equal(extension.isActive, true);
  const { loadedDeactivator } = require(require('node:path').join(extension.extensionPath, 'out', 'live-ui.js'));
  assert.equal(typeof loadedDeactivator(require('node:path').join(extension.extensionPath, 'out', 'extension.js')), 'function', 'The real VS Code host exposes its already-loaded CommonJS module in the shared cache');
  assert.equal(api.getDiagnostics().warning, null, 'Activation must not silently swallow a storage error');
  assert.equal(api.getDiagnostics().liveSwitching, 'experimental');
  assert.equal(api.getDiagnostics().debugEnabled, false, 'Debug mode starts OFF without collecting events');
  const commands = await vscode.commands.getCommands(true);
  console.log('Smoke checkpoint: commands enumerated');
  assert.equal(extension.packageJSON.displayName, 'Antigravity Workbench');
  assert.equal(extension.packageJSON.contributes.views.antigravityAccounts[0].type, 'webview');
  await vscode.commands.executeCommand('antigravityAccounts.accounts.focus');
  console.log('Smoke checkpoint: integrated workbench view resolved');
  for (const suffix of ['openHelp', 'addAccount', 'removeAccount', 'importSnapshot', 'refresh', 'reloadSnapshots', 'openBridgeGuide', 'showCapabilities']) assert.ok(commands.includes(`antigravityAccounts.${suffix}`));
  assert.ok(!commands.some(command => command.startsWith('antigravityAccounts.codex.')), 'Removed feature commands must not be registered');
  for (const suffix of ['login', 'capture', 'switch', 'verify', 'quota', 'quotaCancel', 'restore', 'remove', 'unlock', 'export', 'import', 'acceptance']) assert.ok(commands.includes(`antigravityAccounts.live.${suffix}`));
  for (const suffix of ['open', 'cancel']) assert.ok(commands.includes(`antigravityAccounts.images.${suffix}`));
  for (const suffix of ['copyExtension', 'copyCredentials', 'copyImageOutput', 'openExtension']) assert.ok(commands.includes(`antigravityAccounts.locations.${suffix}`));
  for (const suffix of ['toggle', 'catalog', 'copyDirectory', 'openDirectory', 'preview', 'exportPreview', 'tools', 'dismissCatalog']) assert.ok(commands.includes(`antigravityAccounts.debug.${suffix}`));
  assert.ok(commands.includes('antigravityAccounts.openSettings'));
  const manifest = extension.packageJSON.contributes;
  assert.equal(manifest.commands.find(item => item.command === 'antigravityAccounts.live.export').title, (vscode.env.language.toLowerCase().startsWith('zh') ? '导出账号（.agwenc 加密）' : 'Export accounts (.agwenc encrypted)'));
  assert.equal(manifest.commands.find(item => item.command === 'antigravityAccounts.live.import').title, (vscode.env.language.toLowerCase().startsWith('zh') ? '导入账号（.agwenc 加密）' : 'Import accounts (.agwenc encrypted)'));
  assert.equal(manifest.menus.commandPalette.find(item => item.command === 'antigravityAccounts.debug.catalog').when, 'false');
  assert.ok(!manifest.menus.commandPalette.some(item => item.command === 'antigravityAccounts.debug.tools' && item.when === 'false'));
  await vscode.commands.executeCommand('antigravityAccounts.debug.dismissCatalog');
  assert.match(api.getDiagnostics().liveStatus, /尚未操作/);
  await vscode.commands.executeCommand('antigravityAccounts.reloadSnapshots');
  assert.equal(api.getDiagnostics().warning, null, 'Refresh must not silently swallow a storage error');
  console.log('Smoke checkpoint: local refresh returned');
  await vscode.commands.executeCommand('antigravityAccounts.openBridgeGuide');
  console.log('Smoke checkpoint: bridge guide opened');
  assert.match(vscode.window.activeTextEditor.document.getText(), /不会登录任何账户/);
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor');
  const config = vscode.workspace.getConfiguration('antigravityAccounts');
  assert.equal(config.get('language'), 'zh-CN', 'A clean host starts in Simplified Chinese');
  await vscode.commands.executeCommand('antigravityAccounts.openHelp');
  const help = vscode.workspace.textDocuments.find(document => document.uri.scheme === 'antigravity-workbench-help');
  assert.ok(help);
  const until = async condition => { for (let count = 0; count < 100; count++) { if (condition()) return; await new Promise(resolve => setTimeout(resolve, 20)); } assert.fail('Host locale event did not update the open view/document'); };
  await config.update('language', 'en', vscode.ConfigurationTarget.Global);
  await until(() => /No operation yet/.test(api.getDiagnostics().liveStatus) && /Antigravity Workbench guide/.test(help.getText()));
  assert.equal(config.inspect('language').globalValue, 'en', 'Manual language persists in user settings');
  await config.update('language', 'zh-CN', vscode.ConfigurationTarget.Global);
  await until(() => /尚未操作/.test(api.getDiagnostics().liveStatus) && !/Antigravity Workbench guide/.test(help.getText()));
  await vscode.commands.executeCommand('workbench.action.closeAllEditors');
  await vscode.commands.executeCommand('antigravityAccounts.images.open');
  await vscode.commands.executeCommand('antigravityAccounts.images.cancel');
  await vscode.commands.executeCommand('workbench.action.closeActiveEditor');
  console.log('Extension-host smoke: activation, commands, idle live commands, refresh, guide, persistent manual locale and open-help updates passed');
};
