const test=require('node:test'),assert=require('node:assert/strict');
const {QuotaHistory,initialQuotaHistory,parseQuotaHistory}=require('../out/quota-history'),{accountDisplayFingerprint}=require('../out/quota-presentation'),{ImageRecommendation}=require('../out/image-recommendation');
const A='11111111-1111-4111-8111-111111111111',now=Date.parse('2026-10-09T12:00:00Z');
function memory(){let state=initialQuotaHistory(),tail=Promise.resolve();return{read:async()=>structuredClone(state),transaction(fn){const next=tail.then(()=>{const s=structuredClone(state),r=fn(s);state=parseQuotaHistory(s);return r});tail=next.catch(()=>{});return next}}}
function fixture(){let time=now;const accounts=[{id:A,expectedEmail:'synthetic@example.test',hostCurrent:true,capturedAt:'2026-10-01T00:00:00Z'}],store=memory();const history=new QuotaHistory(store,()=>accounts,()=>{},()=>time),sample={accountId:A,fingerprint:accountDisplayFingerprint(accounts[0]),kind:'bucket',key:'server-bucket',label:'Synthetic',observedAt:new Date(now).toISOString(),fraction:.996,resetAt:null};return{history,store,accounts,sample,setTime:t=>time=t}}
test('history stores actual times, distinguishes unknown and failures, deduplicates old snapshots and cleared observations',async()=>{const f=fixture();await Promise.all([f.history.record(f.sample),f.history.record(f.sample)]);let rows=(await f.history.read()).rows;assert.equal(rows.length,1);assert.equal(rows[0].fraction,.996);f.setTime(now+1000);await f.history.gap(f.sample);await f.history.gap(f.sample);rows=(await f.history.read()).rows;assert.equal(rows.length,2);assert.equal(rows[1].observedAt,null);assert.equal(rows[1].fraction,null);assert.equal(rows[0].observedAt,f.sample.observedAt);await f.history.record({...f.sample,observedAt:new Date(now+1000).toISOString(),fraction:null});assert.equal((await f.history.read()).rows.at(-1).status,'unknown');await f.history.clear();await f.history.record(f.sample);assert.equal((await f.history.read()).rows.length,0)});
test('bucket identities and exact image endpoint/model identities cannot collide; account replacements remove all old observations',async()=>{const f=fixture();await f.history.record(f.sample);await f.history.record({...f.sample,kind:'image-model',key:JSON.stringify(['daily','server-bucket'])});assert.equal((await f.history.read({kind:'bucket'})).rows.length,1);assert.equal((await f.history.read({kind:'image-model'})).rows.length,1);f.accounts[0].capturedAt='2026-10-09T12:01:00Z';await f.history.reconcile();assert.equal((await f.store.read()).rows.length,0);await f.history.record(f.sample);assert.equal((await f.history.read()).rows.length,0);f.accounts.splice(0);await f.history.reconcile();assert.equal((await f.store.read()).seen.length,0)});
test('retention and bounded storage preserve newest records; invalid/future inputs cannot invent readings',async()=>{const f=fixture();await f.history.record({...f.sample,observedAt:'invalid'});await f.history.record({...f.sample,observedAt:new Date(now+1).toISOString()});assert.equal((await f.history.read()).rows.length,0);await f.history.record(f.sample);f.setTime(now+2*86400000);await f.history.settings(1);assert.equal((await f.history.read()).rows.length,0);await assert.rejects(f.history.settings(91),/INVALID/);await assert.rejects(f.store.transaction(s=>s.rows.push({})),/INVALID/);await f.store.transaction(s=>{s.rows=Array.from({length:5000},(_,i)=>({id:String(i),...f.sample,eventAt:new Date(now+2*86400000).toISOString(),observedAt:new Date(now+2*86400000).toISOString(),fingerprint:f.sample.fingerprint,key:'x'.repeat(999),status:'ready'}))});await f.history.reconcile();assert.ok(Buffer.byteLength(JSON.stringify(await f.store.read()))<=1536*1024);assert.ok((await f.history.read()).rows.length<5000)});
function recommendation(read){const accounts=Array.from({length:3},(_,i)=>({id:A.replace(/^11111111/,String(i+1).padStart(8,'0')),expectedEmail:`synthetic${i}@example.test`,hostCurrent:true}));const observed=[];const r=new ImageRecommendation(()=>accounts,read,()=>{},x=>observed.push(x),()=>now);return{accounts,r,observed}}
const snapshot=(id,model,endpoint,fraction=.8,queriedAt=new Date(now).toISOString())=>({accountId:id,modelId:model,endpoint,remainingFraction:fraction,resetAt:null,queriedAt});
test('recommendations use only exact fresh positive selected model quotas; unknown/old/zero/wrong models never chosen',async()=>{for(const bad of [null,0,.996]){const f=recommendation(async(id,m,_s,e)=>snapshot(id,m,e,bad));await f.r.start('image-model','daily');assert.equal(!!f.r.choose(f.accounts[0].id),bad===.996)}for(const change of [s=>({...s,modelId:'other'}),s=>({...s,queriedAt:new Date(now-60000).toISOString()}),s=>({...s,endpoint:'production'})]){const f=recommendation(async(id,m,_s,e)=>change(snapshot(id,m,e)));await f.r.start('image-model','daily');assert.equal(f.r.choose(f.accounts[0].id),undefined)}});
test('duplicate requests are bounded and serialized, cancel can restart immediately and late results are isolated',async()=>{let resolve,calls=0,active=0,max=0;const f=recommendation(async(id,m,_s,e)=>{calls++;active++;max=Math.max(max,active);if(calls===1)await new Promise(r=>resolve=r);active--;return snapshot(id,m,e)});const first=f.r.start('old-model','daily');assert.equal(f.r.start('old-model','daily'),first);f.r.cancel();assert.equal(f.r.getState().rows[0].phase,'cancelled');const next=f.r.start('new-model','daily');await next;resolve();await first;assert.equal(f.r.getState().modelId,'new-model');assert.ok(f.r.getState().rows.every(r=>r.snapshot.modelId==='new-model'));assert.equal(calls,4);assert.equal(f.observed.length,3);assert.ok(max<=2);const bounded=recommendation(async(id,m,_s,e)=>snapshot(id,m,e));bounded.accounts.push(...Array.from({length:60},(_,i)=>({...bounded.accounts[0],id:String(i)})));await bounded.r.start('model','daily');assert.equal(bounded.r.getState().rows.length,50)});
test('replaced accounts cannot receive delayed recommendation result or be selected',async()=>{let resolve;const f=recommendation(async(id,m,_s,e)=>{await new Promise(r=>resolve=r);return snapshot(id,m,e)});f.accounts.splice(1);const pending=f.r.start('model','daily');f.accounts[0].capturedAt='replaced';resolve();await pending;assert.equal(f.r.choose(f.accounts[0].id),undefined);assert.equal(f.r.getState().rows[0].phase,'error')});
test('independent processes deduplicate history, preserve clear watermarks and reject a delayed deleted account',async()=>{
 const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),{PrivateState}=require('../out/private-state');
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'ag-history-processes-')));
 try{
  const account={id:A,expectedEmail:'synthetic@example.test',hostCurrent:true,capturedAt:'2026-10-01T00:00:00Z'};
  await fs.writeFile(path.join(root,'accounts.json'),JSON.stringify([account]));
  const store=new PrivateState(path.join(root,'private'),parseQuotaHistory,initialQuotaHistory);
  const launch=action=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.join(__dirname,'fixtures/history-worker.cjs'),root,action],{stdio:['ignore','ignore','pipe']});let errors='';child.stderr.on('data',d=>errors+=d);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(errors)))});
  await Promise.all([launch('record'),launch('record')]);assert.equal((await store.read()).rows.length,1);
  await Promise.all([launch('clear'),launch('record')]);assert.equal((await store.read()).rows.length,0);assert.equal((await store.read()).seen.length,1);
  const delayed=launch('held-record');let ready=false;
  for(let i=0;i<500;i++){try{await fs.stat(path.join(root,'ready'));ready=true;break}catch{await new Promise(resolve=>setTimeout(resolve,10))}}
  assert.equal(ready,true);await fs.writeFile(path.join(root,'accounts.json'),'[]');
  const cleanup=launch('reconcile');await fs.writeFile(path.join(root,'release'),'synthetic');await Promise.all([cleanup,delayed]);
  assert.equal((await store.read()).rows.length,0);assert.equal((await store.read()).seen.length,0);
 }finally{await fs.rm(root,{recursive:true,force:true})}
});
