// Production renderer fixtures. Synthetic accounts, quota and local preview pixels;
// no account access, OAuth or image requests. See review-i18n.py for browser checks.
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const original=Module._load;Module._load=function(n,...args){return n==='vscode'?{}:original.call(this,n,...args)};
const {renderWorkbench}=require('../out/workbench-view');Module._load=original;
const {directImageHtml}=require('../out/direct-image-view'),{setLanguage,t,localizeMessage}=require('../out/i18n'),{zhCN}=require('../out/i18n-zh');
const key=text=>Object.keys(zhCN).find(k=>zhCN[k]===text),directory=path.resolve('.test-results/i18n');fs.mkdirSync(directory,{recursive:true});
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',task='33333333-3333-4333-8333-333333333333',model='gemini-nano-banana-2.1';
const preview='data:image/png;base64,'+require('../test/fixtures/png-fixture.cjs').png().toString('base64');
const account={id:A,label:'Synthetic official A',expectedEmail:'synthetic.a@example.test',hostCurrent:true,capturedAt:new Date().toISOString(),identitySource:'hub',quota:{phase:'ready',snapshot:{source:'server',email:'synthetic.a@example.test',observedAt:'2026-10-07T12:00:00Z',buckets:[{label:'Gemini · synthetic',remaining:.88,resetAt:'2026-10-08T00:00:00Z'},{label:'Claude · synthetic',remaining:.12,resetAt:null}]}}};
const themes={dark:'--vscode-sideBar-background:#181b20;--vscode-editor-background:#20252c;--vscode-foreground:#e7ebf1;--vscode-descriptionForeground:#9ca7b7;--vscode-widget-border:#343d49;--vscode-button-background:#4774cf;--vscode-button-secondaryBackground:#292f38;--vscode-input-background:#14171c;--vscode-input-foreground:#e7ebf1;--vscode-input-border:#343d49;',light:'--vscode-sideBar-background:#f3f4f6;--vscode-editor-background:#ffffff;--vscode-foreground:#252b34;--vscode-descriptionForeground:#5c6674;--vscode-widget-border:#ccd1d9;--vscode-button-background:#3568c8;--vscode-button-secondaryBackground:#e5e9ef;--vscode-input-background:#ffffff;--vscode-input-foreground:#252b34;--vscode-input-border:#ccd1d9;'};
const cases=[];for(const language of ['zh-CN','en']){setLanguage(language);for(const [theme,css]of Object.entries(themes)){
 const decorate=html=>html.replace('</head>',`<style nonce="fixture">:root{${css}}.fixture-caption{font-size:10px;opacity:.75;margin-bottom:12px;overflow-wrap:anywhere}</style></head>`).replace('<main>','<main><p class="fixture-caption">SYNTHETIC DATA · NO ACCOUNT / IMAGE REQUESTS</p>').replace('<script nonce="fixture">',`<script nonce="fixture">let persisted={};globalThis.sent=[];globalThis.acquireVsCodeApi=()=>({getState:()=>persisted,setState:s=>{persisted=s},postMessage:m=>sent.push(m)});</script><script nonce="fixture">`);
 for(const save of ['saved','update','unknown','unsaved']){const state={version:require('../package.json').version,accounts:[account,{...account,id:B,label:'Synthetic image B',expectedEmail:'synthetic.b@example.test',quota:undefined}],activeEmail:save==='unknown'?undefined:save==='unsaved'?'synthetic.unsaved@example.test':account.expectedEmail,activeVerifiedAt:new Date().toISOString(),currentLoginSave:save==='saved'?'saved':save==='update'?'update':undefined,snapshots:[],busy:false,pending:false,status:t(key('准备就绪')),warning:null,environment:{available:true,message:'Synthetic local host'},official:{available:true,message:'Synthetic official extension'}};
 const name=`workbench-${language}-${theme}-${save}`,file=path.join(directory,name+'.html');fs.writeFileSync(file,decorate(renderWorkbench(state,'fixture')));for(const width of [160,240,320,410,900,1440])cases.push({name,view:'workbench',language,theme,save,file,width});}
 const name=`images-${language}-${theme}`,file=path.join(directory,name+'.html');let html=decorate(directImageHtml('fixture'));fs.writeFileSync(file,html);
 for(const width of [240,320,410,900,1440])cases.push({name,view:'images',language,theme,file,width});}
 const state={type:'state',busy:false,status:t(key('已保存 {p0} 张图片（PNG / JPEG）'),{p0:1}),storageNotice:'',accountStatus:'',accountBlocked:false,choicesLoading:false,canCheckAccount:true,choices:{accounts:[{id:A,label:'Synthetic official A'+t(key('（当前登录）'))},{id:B,label:'Synthetic image B'}],models:[{id:model,label:model}]},draft:{prompt:'中文 user prompt <img onerror=x>',accountId:B,modelId:model,ratio:'16:9',count:2,size:'2K',quality:'detail',followCurrent:false},outputDirectory:'/synthetic/project',outputName:'project',references:['reference-synthetic.png'],referenceImages:[{name:'reference-synthetic.png',index:0,preview}],referenceRevision:3,editorTarget:{id:0,canInsert:false},tasks:[{id:task,createdAt:'2026-10-07T12:00:00Z',promptSummary:'Synthetic geometric preview',accountId:B,accountLabel:'Synthetic image B',modelId:model,ratio:'16:9',size:'2K',count:1,quality:'detail',phase:'complete',status:t(key('已保存 {p0} 张图片（PNG / JPEG）'),{p0:1}),images:[{name:'synthetic.png',index:0,width:2,height:2,preview}]}],imageQuota:{loading:false,stale:false,snapshot:{accountId:B,modelId:model,endpoint:'daily',remainingFraction:.99999,resetAt:'2026-10-08T00:00:00Z',queriedAt:'2026-10-07T12:00:00Z'}},recentDiagnostic:localizeMessage('暂无最近一次图片失败记录')};fs.writeFileSync(path.join(directory,'state-'+language+'.json'),JSON.stringify(state));}
setLanguage('zh-CN');fs.writeFileSync(path.join(directory,'cases.json'),JSON.stringify(cases,null,2)+'\n');console.log('Generated '+cases.length+' production renderer checks');
