import { randomBytes } from 'node:crypto';
import { clientI18n, ht, locale } from './i18n';
/** The form is never replaced by a state refresh. Text enters the DOM as text. */
export function automationHtml(cspSource: string): string {
  const text = (key: Parameters<typeof ht>[0]) => `<span data-i18n="${key}">${ht(key)}</span>`;
  const nonce = randomBytes(16).toString('hex');
  const input = (id: string, key: Parameters<typeof ht>[0], value: string, type = 'text') => `<label for="${id}">${text(key)}</label><input id="${id}" type="${type}" value="${value}">`;
  const check = (id: string, key: Parameters<typeof ht>[0]) => `<label><input id="${id}" type="checkbox"> ${text(key)}</label>`;
  return `<!doctype html><html lang="${locale()}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; img-src ${cspSource}"><style nonce="${nonce}">
  *{box-sizing:border-box}body{margin:0;padding:16px;color:var(--vscode-foreground);background:var(--vscode-editor-background);font:13px/1.5 var(--vscode-font-family);overflow-wrap:anywhere}main{max-width:780px;margin:auto;min-width:0}h1{font-size:20px}h2{font-size:15px}p{color:var(--vscode-descriptionForeground)}section,article{border:1px solid var(--vscode-widget-border);border-radius:7px;padding:12px;margin:12px 0;min-width:0}form{display:grid;gap:6px}button,input,select{font:inherit;min-width:0;max-width:100%;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-widget-border);padding:7px}input:not([type=checkbox]),select{width:100%}button{cursor:pointer;white-space:normal;overflow-wrap:anywhere;color:var(--vscode-button-foreground);background:var(--vscode-button-background);border-radius:4px}button:disabled{opacity:.5}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--vscode-focusBorder)}.actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.notice{white-space:pre-wrap}.result{font-size:11px}.top{display:flex;gap:6px;flex-wrap:wrap}details summary{cursor:pointer}label{display:block}ul{padding-left:18px}
  </style></head><body><main><div class="top"><button id="zh">简体中文</button><button id="en">English</button></div><h1>${text('automation.title')}</h1><p>${text('automation.scope')}</p><p id="cost">${text('automation.cost')}</p>${check('master','automation.master')}
  <section><h2>${text('privacy.title')}</h2>${check('privacy','privacy.title')}<p>${text('privacy.hint')}</p></section>
  <section><h2>${text('alerts.title')}</h2><p>${text('alerts.hint')}</p>${check('low','alerts.low')}${check('exhausted','alerts.exhausted')}${check('recovered','alerts.recovered')}${input('threshold','alerts.threshold','10','number')}<button id="save-alerts">${text('alerts.save')}</button></section>
  <section><form id="task-form"><label for="account">${text('automation.account')}</label><select id="account"></select><button id="models" type="button">${text('automation.models')}</button><label for="endpoint">Endpoint</label><select id="endpoint"><option value="daily">Daily</option><option value="production">Production</option></select><label for="model">${text('automation.model')}</label><select id="model"></select>
  ${input('timezone','automation.timezone','Etc/UTC')}${input('times','automation.times','08:00')}${input('weekdays','automation.weekdays','0,1,2,3,4,5,6')}${input('budget','automation.budget','8','number')}<div class="actions"><button id="save" type="submit">${text('automation.save')}</button><button id="preview" type="button">${text('automation.preview')}</button><button id="new" type="button">${text('automation.new')}</button></div></form><p id="preview-result" class="notice" aria-live="polite"></p></section>
  <p id="notice" role="status" class="notice" aria-live="polite"></p><div id="tasks"></div><section><details open><summary>${text('automation.result')}</summary><div id="results"></div></details></section>
  </main><script nonce="${nonce}">${clientI18n()}
  const api=acquireVsCodeApi(),$=id=>document.getElementById(id);let state,editing='',revision='',wanted='',catalogKey='',sequence=0,alertsDirty=false;const pending=new Set();
  const send=(type,data={})=>{if(type!=='models'&&pending.has(type))return;pending.add(type);if(type==='enable')$('master').disabled=true;api.postMessage({type,requestId:String(++sequence),...data})};
  const selection=()=>({accountId:$('account').value,endpoint:$('endpoint').value});
  const schedule=()=>({timezone:$('timezone').value.trim(),times:$('times').value.split(',').map(x=>x.trim()),weekdays:$('weekdays').value.split(',').map(x=>Number(x.trim()))});
  const resetModels=()=>{catalogKey='';$('model').replaceChildren();send('models',selection())};
  $('models').onclick=resetModels;$('account').onchange=resetModels;$('endpoint').onchange=resetModels;
  $('task-form').onsubmit=event=>{event.preventDefault();send('save',{...selection(),id:editing,revision,modelId:$('model').value,schedule:schedule(),outputBudget:Number($('budget').value),catalogKey})};
  $('preview').onclick=()=>send('preview',{schedule:schedule()});$('master').onchange=()=>send('enable',{enabled:$('master').checked});$('privacy').onchange=()=>send('privacy',{hidden:$('privacy').checked});
  for(const key of ['low','exhausted','recovered'])$(key).onchange=()=>alertsDirty=true;$('threshold').oninput=()=>alertsDirty=true;
  $('save-alerts').onclick=()=>send('alerts',{low:$('low').checked,exhausted:$('exhausted').checked,recovered:$('recovered').checked,threshold:Number($('threshold').value)});
  $('zh').onclick=()=>send('language',{language:'zh-CN'});$('en').onclick=()=>send('language',{language:'en'});
  $('new').onclick=()=>{editing='';revision='';wanted='';$('save').textContent=tr('automation.save');$('preview-result').textContent=''};
  const button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=fn;return b};
  function renderTasks(){const root=$('tasks'),focus=document.activeElement,scroll=window.scrollY,keep=new Set();
    for(const t of state.tasks){let row=root.querySelector('[data-task="'+t.id+'"]');if(!row){row=document.createElement('article');row.dataset.task=t.id;row.innerHTML='<strong></strong><p></p><div class="actions"></div>';root.append(row)}keep.add(row);row.querySelector('strong').textContent=t.accountLabel+' · '+t.modelId;row.querySelector('p').textContent=(t.enabled?tr('automation.enabled'):tr('automation.paused'))+' · '+tr('automation.next',{p0:t.nextLabel});
    const a=row.querySelector('.actions');if(!a.childElementCount){for(const action of ['edit','resume','pause','test','cancel','remove']){const b=button('',()=>{const current=state.tasks.find(x=>x.id===t.id);if(action==='edit'){editing=current.id;revision=current.revision;wanted=current.modelId;$('account').value=current.accountId;$('endpoint').value=current.endpoint;$('timezone').value=current.schedule.timezone;$('times').value=current.schedule.times.join(',');$('weekdays').value=current.schedule.weekdays.join(',');$('budget').value=String(current.outputBudget);$('save').textContent=tr('automation.update');resetModels();$('account').focus()}else send(action,{id:t.id})});b.dataset.action=action;a.append(b)}}
    for(const b of a.children){b.textContent=tr('automation.'+b.dataset.action);b.hidden=b.dataset.action==='resume'?t.enabled:b.dataset.action==='pause'?!t.enabled:false;b.disabled=t.running&&['test','resume','edit'].includes(b.dataset.action)}
    }for(const row of [...root.children])if(!keep.has(row))row.remove();if(!state.tasks.length)root.textContent=tr('automation.empty');else if(root.firstChild?.nodeType===3)root.firstChild.remove();if(focus?.isConnected&&document.hasFocus())focus.focus({preventScroll:true});window.scrollTo(0,scroll);
  }
  window.addEventListener('message',event=>{const m=event.data;if(!m)return;if(m.requestType)pending.delete(m.requestType);
    if(m.type==='state'){state=m.state;if(!pending.has('enable'))$('master').checked=state.enabled;$('privacy').checked=state.hidden;for(const key of ['low','exhausted','recovered'])if(!alertsDirty&&document.activeElement!==$(key))$(key).checked=state.alerts[key];if(!alertsDirty&&document.activeElement!==$('threshold'))$('threshold').value=state.alerts.threshold;
      const selected=$('account').value,old=[...$('account').options].map(x=>[x.value,x.textContent]);if(JSON.stringify(old)!==JSON.stringify(state.accounts.map(a=>[a.id,a.label]))){$('account').replaceChildren(...state.accounts.map(a=>new Option(a.label,a.id)));if(state.accounts.some(a=>a.id===selected))$('account').value=selected;else{catalogKey='';$('model').replaceChildren()}}
      renderTasks();$('results').replaceChildren(...state.instances.map(i=>{const p=document.createElement('p');p.className='result';p.textContent=i.label;return p}));}
    if(m.type==='models'&&m.accountId===$('account').value&&m.endpoint===$('endpoint').value){catalogKey=m.catalogKey;$('model').replaceChildren(...m.models.map(x=>new Option(x.label,x.id)));if(wanted&&m.models.some(x=>x.id===wanted))$('model').value=wanted;wanted='';}
    if(m.type==='preview')$('preview-result').textContent=m.labels.join('\\n');if(m.type==='notice')$('notice').textContent=m.text;
    if(m.type==='language'){language=m.language;applyLanguage();if(state)renderTasks();$('save').textContent=tr(editing?'automation.update':'automation.save')}if(m.type==='complete'){pending.delete(m.requestType);if(m.requestType==='enable'){$('master').disabled=false;if(state)$('master').checked=state.enabled}if(m.requestType==='alerts')alertsDirty=false}
  });api.postMessage({type:'ready'});
  </script></body></html>`;
}
