import { clientI18n, ht, locale } from './i18n';
import { imageQuotaPercent } from './image-quota';
import { imageWorkspaceStyles } from './direct-image-styles';
import { imageResultStyles, imageDraftMarkup, imageComparisonMarkup, imageResultScript } from './image-result-view';
import { imageLayoutScript, readImageLayout, type ImageLayout } from './direct-image-layout';

/** Production image workspace. All variable text is assigned with textContent. */
export function directImageHtml(nonce: string, source = '', layout: ImageLayout = readImageLayout(undefined)): string {
  return `<!doctype html><html lang="${locale()}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${source} data:; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'">
<style nonce="${nonce}">
${imageWorkspaceStyles}
${imageResultStyles}
</style></head><body><main>
<header class="page-heading"><div><p class="eyebrow">ANTIGRAVITY WORKBENCH</p><h1><span data-i18n="directImageView.5c83dc5baa">${ht("directImageView.5c83dc5baa")}</span></h1></div><div class="layout-toolbar"><button id="resultsToggle" class="secondary" aria-controls="results" aria-expanded="true"><span data-i18n="directImageView.e6fe633174">${ht("directImageView.e6fe633174")}</span></button></div></header><p id="layoutNotice" class="layout-notice muted" role="status"></p>
<div class="workspace" id="workspace"><section class="panel composer" aria-label="${ht("directImageView.bab43de50d")}" data-i18n-aria-label="directImageView.bab43de50d">
<section class="form-section" aria-labelledby="accountHeading"><div class="section-heading"><div class="section-title"><span class="step" aria-hidden="true">1</span><h2 id="accountHeading"><span data-i18n="directImageView.bb772eb32b">${ht("directImageView.bb772eb32b")}</span></h2></div><button id="checkAccount" class="quiet" hidden><span data-i18n="directImageView.c25fb86b1e">${ht("directImageView.c25fb86b1e")}</span></button></div>
<div class="row"><div><label for="account"><span data-i18n="directImageView.bc0b8faa5e">${ht("directImageView.bc0b8faa5e")}</span></label><select id="account" title="${ht("directImageView.e7f1072e63")}" data-i18n-title="directImageView.e7f1072e63"></select></div><div><label for="model"><span data-i18n="directImageView.48156e412e">${ht("directImageView.48156e412e")}</span></label><select id="model"></select><button id="favoriteModel" class="quiet" disabled><span data-i18n="quota.imageFavorite">${ht("quota.imageFavorite")}</span></button></div></div>
<div class="account-check"><p id="accountStatus" class="notice account-notice" role="status"></p></div>
<section class="image-quota" aria-label="${ht("directImageView.498ba61d8f")}" data-i18n-aria-label="directImageView.498ba61d8f"><div class="quota-top"><div class="quota-reading"><strong id="imageQuotaStatus" role="status" aria-live="polite"><span data-i18n="directImageView.4712cf60be">${ht("directImageView.4712cf60be")}</span></strong><span id="quotaState" class="quota-state"></span></div><button id="queryQuota" class="quiet" title="${ht("directImageView.f4a6bf9a27")}" data-i18n-title="directImageView.f4a6bf9a27"><span data-i18n="directImageView.f73840a356">${ht("directImageView.f73840a356")}</span></button></div><div class="quota-times"><span id="imageQuotaReset"></span><span id="imageQuotaTime"></span></div><p id="imageQuotaError" class="notice account-notice" role="alert"></p><details class="quota-info"><summary><span data-i18n="directImageView.7f37efe0f1">${ht("directImageView.7f37efe0f1")}</span></summary><p><span data-i18n="directImageView.ee75db7b42">${ht("directImageView.ee75db7b42")}</span></p></details></section>
<section class="image-quota"><div class="quota-top"><button id="compareAccounts" class="quiet"><span data-i18n="recommend.compare">${ht('recommend.compare')}</span></button><button id="cancelCompareAccounts" class="quiet" hidden><span data-i18n="recommend.cancel">${ht('recommend.cancel')}</span></button></div><p><span data-i18n="recommend.hint">${ht('recommend.hint')}</span></p><div id="recommendations"></div></section>
</section>
<section class="form-section" aria-labelledby="promptHeading"><div class="section-heading"><div class="section-title"><span class="step" aria-hidden="true">2</span><h2 id="promptHeading"><span data-i18n="directImageView.794f6bed23">${ht("directImageView.794f6bed23")}</span></h2></div></div>
${imageDraftMarkup()}
<label for="prompt"><span data-i18n="directImageView.e85f0c1ba1">${ht("directImageView.e85f0c1ba1")}</span></label><textarea id="prompt" maxlength="12000" placeholder="${ht("directImageView.a8de3de93b")}" data-i18n-placeholder="directImageView.a8de3de93b"></textarea>
<div class="references-section"><div class="reference-heading"><div><h3><span data-i18n="directImageView.e93aea8dae">${ht("directImageView.e93aea8dae")}</span><span class="muted"><span data-i18n="directImageView.002b1a1484">${ht("directImageView.002b1a1484")}</span></span></h3><span id="referenceCount" class="reference-count">0 / 3</span></div><div><button id="chooseReferences" class="quiet"><span data-i18n="directImageView.bc35022a3a">${ht("directImageView.bc35022a3a")}</span></button><button id="clearReferences" class="quiet" hidden><span data-i18n="directImageView.1b59091409">${ht("directImageView.1b59091409")}</span></button></div></div><div id="references" class="reference-empty"><p class="muted"><span data-i18n="directImageView.eac13cbee8">${ht("directImageView.eac13cbee8")}</span></p></div><div id="referenceList" class="reference-list"></div><p id="referenceHelp" class="reference-help muted"><span data-i18n="directImageView.c303e09487">${ht("directImageView.c303e09487")}</span></p></div>
</section>
<section class="form-section" aria-labelledby="settingsHeading"><div class="section-heading"><div class="section-title"><span class="step" aria-hidden="true">3</span><h2 id="settingsHeading"><span data-i18n="directImageView.fe9746d71a">${ht("directImageView.fe9746d71a")}</span></h2></div></div>
<div class="row"><div><label for="ratio"><span data-i18n="directImageView.5c6d39030a">${ht("directImageView.5c6d39030a")}</span></label><select id="ratio"><option>1:1</option><option>16:9</option><option>9:16</option><option>4:3</option><option>3:4</option><option>3:2</option><option>2:3</option></select></div><div><label for="count"><span data-i18n="directImageView.a2e2ce97f2">${ht("directImageView.a2e2ce97f2")}</span></label><select id="count"><option value="1" data-i18n="directImageView.35cf44ac0f">${ht("directImageView.35cf44ac0f")}</option><option value="2" data-i18n="directImageView.4bcc1247f9">${ht("directImageView.4bcc1247f9")}</option><option value="3" data-i18n="directImageView.6488fcdda7">${ht("directImageView.6488fcdda7")}</option><option value="4" data-i18n="directImageView.5641872dab">${ht("directImageView.5641872dab")}</option></select></div></div>
<details id="advanced" class="settings"><summary><span data-i18n="directImageView.ecd8a97ef9">${ht("directImageView.ecd8a97ef9")}</span></summary><div class="row"><div><label for="size"><span data-i18n="directImageView.246df7d8db">${ht("directImageView.246df7d8db")}</span></label><select id="size"><option value="auto" data-i18n="directImageView.7eb336e42c">${ht("directImageView.7eb336e42c")}</option><option>1K</option><option>2K</option><option>4K</option></select></div><div><label for="quality"><span data-i18n="directImageView.5ce4ed5694">${ht("directImageView.5ce4ed5694")}</span></label><select id="quality"><option value="auto" data-i18n="directImageView.7eb336e42c">${ht("directImageView.7eb336e42c")}</option><option value="detail" data-i18n="directImageView.c4191d4913">${ht("directImageView.c4191d4913")}</option></select></div></div></details>
<div class="output-location"><p id="output" class="muted"></p><button id="chooseOutput" class="quiet"><span data-i18n="directImageView.edfa33a3f4">${ht("directImageView.edfa33a3f4")}</span></button></div>
</section><div class="actions-section"><p id="storageNotice" class="notice account-notice" role="status"></p><button id="saveRecords" class="secondary" hidden><span data-i18n="directImageView.3d586526ce">${ht("directImageView.3d586526ce")}</span></button>
<div class="actions"><button id="generate" disabled><span data-i18n="directImageView.71c9cf3da9">${ht("directImageView.71c9cf3da9")}</span></button><button id="cancel" class="secondary" disabled><span data-i18n="directImageView.2cd0f3be87">${ht("directImageView.2cd0f3be87")}</span></button></div><p id="formHint" class="notice muted" role="status">${ht("directImageView.validationHint")}</p><p class="consent-note muted"><span data-i18n="directImageView.f5f804c6f2">${ht("directImageView.f5f804c6f2")}</span></p><p id="status" class="notice" role="status"></p></div>
<div class="utility"><button id="recover" class="quiet"><span data-i18n="directImageView.3fd756c921">${ht("directImageView.3fd756c921")}</span></button><details id="imageDebug"><summary><span data-i18n="directImageView.98d5eb455f">${ht("directImageView.98d5eb455f")}</span></summary><details id="history"><summary id="historyLabel"><span data-i18n="directImageView.01baaf1f55">${ht("directImageView.01baaf1f55")}</span></summary><p class="muted history-note"><span data-i18n="directImageView.823ac0b2e1">${ht("directImageView.823ac0b2e1")}</span></p><pre id="operationHistory"></pre></details><details id="diagnostic"><summary><span data-i18n="directImageView.d4e863da67">${ht("directImageView.d4e863da67")}</span></summary><p id="recentDiagnostic" class="path muted"></p></details></details></div>
</section><div id="resultsSplitter" class="results-splitter" role="separator" tabindex="0" aria-label="${ht("directImageView.f3ac56ac7f")}" data-i18n-aria-label="directImageView.f3ac56ac7f" aria-orientation="vertical" aria-controls="results" title="${ht("directImageView.a85ca80d62")}" data-i18n-title="directImageView.a85ca80d62"></div><section id="results" class="results" aria-label="${ht("directImageView.f6df2f4407")}" data-i18n-aria-label="directImageView.f6df2f4407"><div class="results-heading"><h2><span data-i18n="directImageView.15a6c10c38">${ht("directImageView.15a6c10c38")}</span></h2><span id="taskCount" class="muted"><span data-i18n="directImageView.7abb0d7b0c">${ht("directImageView.7abb0d7b0c")}</span></span></div>${imageComparisonMarkup()}<div id="empty" class="empty"><p class="empty-icon" aria-hidden="true">▧</p><h2><span data-i18n="directImageView.9658e5464f">${ht("directImageView.9658e5464f")}</span></h2><p class="muted"><span data-i18n="directImageView.ab1a814996">${ht("directImageView.ab1a814996")}</span></p></div><div id="tasks" class="task-list"></div><p class="muted history-note"><span data-i18n="directImageView.dd26206e56">${ht("directImageView.dd26206e56")}</span></p></section></div>
</main><script nonce="${nonce}">
const api=acquireVsCodeApi(),el=id=>document.getElementById(id);let busy=false,accountBlocked=false,choicesLoading=false,accountRetryPending=false,quotaLoading=false,storageBlocked=false,referenceRevision=0,referenceCount=0,outputReady=false,draftRevision=0,draftEpoch=0,actionRevision=0;
const local=()=>api.getState?.()||{};
const persist=(key,value)=>api.setState?.({...local(),[key]:value});
${clientI18n()}
${imageLayoutScript(layout)}
for(const id of ['advanced','imageDebug','history','diagnostic']){el(id).open=local()[id]===true;el(id).addEventListener('toggle',()=>{persist(id,el(id).open);if(id==='history'){el('historyLabel').textContent=el(id).open?tr("directImageView.9d3b4f6443"):tr("directImageView.01baaf1f55");if(el(id).open)api.postMessage({type:'history'})}})}
const draft=()=>({prompt:el('prompt').value,accountId:el('account').value==='@current'?'':el('account').value,modelId:el('model').value,ratio:el('ratio').value,count:Number(el('count').value),size:el('size').value,quality:el('quality').value,draftRevision});
const renderBusy=()=>{el('favoriteModel').disabled=busy||choicesLoading||!el('model').value;el('queryQuota').disabled=busy||accountBlocked||choicesLoading||quotaLoading;el('queryQuota').textContent=quotaLoading?tr("directImageView.d302f90b09"):el('imageQuotaTime').textContent?tr("directImageView.aee8874341"):tr("directImageView.f73840a356");for(const id of ['account','model','prompt','ratio','count','size','quality','chooseOutput','chooseReferences','clearReferences','recover'])el(id).disabled=busy;const missingPrompt=!el('prompt').value.trim();el('generate').disabled=busy||accountBlocked||storageBlocked||missingPrompt||!outputReady;el('generate').textContent=busy?tr("directImageView.574ec7517d"):tr("directImageView.71c9cf3da9");el('formHint').textContent=missingPrompt?tr("directImageHttpError.promptRequired"):!outputReady?tr("directImageHttpError.outputRequired"):'';el('cancel').disabled=!busy&&!choicesLoading&&!accountRetryPending;el('checkAccount').disabled=busy||choicesLoading;el('saveRecords').disabled=busy;el('detachIteration').disabled=busy;for(const b of document.querySelectorAll('.reference-remove'))b.disabled=busy;for(const b of document.querySelectorAll('.result-action,.draft-action,.compare-side select')){if(busy)b.disabled=true}};
const send=(type,extra={})=>{if(busy&&type!=='cancel')return;if(!['cancel','compareAccounts','cancelCompareAccounts'].includes(type))busy=true;api.postMessage({type,...draft(),...extra,actionRevision:++actionRevision});renderBusy()};
const sendDraft=()=>{if(busy)return;++draftRevision;api.postMessage({type:'draft',...draft()});renderBusy()};
for(const id of ['prompt','model','ratio','count','size','quality'])el(id).addEventListener('change',sendDraft);el('prompt').addEventListener('input',sendDraft);
el('account').addEventListener('change',()=>{if(busy)return;++draftRevision;const prior=draft();accountBlocked=true;el('model').replaceChildren();api.postMessage({type:'selectAccount',selection:el('account').value,...prior});renderBusy()});el('checkAccount').onclick=()=>{if(busy||choicesLoading)return;choicesLoading=true;renderBusy();api.postMessage({type:'checkAccount'})};
el('favoriteModel').onclick=()=>api.postMessage({type:'favoriteModel',modelId:el('model').value});
el('compareAccounts').onclick=()=>send('compareAccounts');el('cancelCompareAccounts').onclick=()=>send('cancelCompareAccounts');el('queryQuota').onclick=()=>{if(busy||accountBlocked||choicesLoading||quotaLoading)return;quotaLoading=true;renderBusy();api.postMessage({type:'queryQuota'})};
el('saveRecords').onclick=()=>api.postMessage({type:'saveRecords'});
el('chooseOutput').onclick=()=>send('output');el('chooseReferences').onclick=()=>send('references');el('clearReferences').onclick=()=>send('clearReferences',{revision:referenceRevision});el('recover').onclick=()=>send('recover');el('generate').onclick=()=>send('generate',draft());el('cancel').onclick=()=>send('cancel');
const options=(id,rows)=>{const prior=el(id).value;el(id).replaceChildren();for(const row of rows){const option=document.createElement('option');option.value=row.id;option.textContent=row.label+(row.unavailable?tr("directImageView.56d1e244aa"):'');option.disabled=!!row.unavailable;el(id).append(option)}if([...el(id).options].some(x=>x.value===prior&&!x.disabled))el(id).value=prior};
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const quotaPercent=value=>(${imageQuotaPercent.toString()})(value,tr("imageQuota.bafbf5e6f8"));
const renderRecommendations=s=>{const root=el('recommendations');const rows=s?.rows||[];const keep=new Set(rows.map(r=>r.accountId));for(const n of [...root.children])if(!keep.has(n.dataset.account))n.remove();const fresh=rows.filter(r=>r.usable),best=fresh.length?Math.max(...fresh.map(r=>r.snapshot.remainingFraction)):null;for(const r of [...rows].sort((a,b)=>Number(b.usable)-Number(a.usable)||((b.snapshot?.remainingFraction||0)-(a.snapshot?.remainingFraction||0)))){let card=[...root.children].find(n=>n.dataset.account===r.accountId);if(!card){card=node('div','quota-info');card.dataset.account=r.accountId;root.append(card)}let text=card.querySelector('p'),button=card.querySelector('button');if(!text){text=node('p');button=node('button','quiet');button.onclick=()=>send('chooseRecommended',{accountId:r.accountId});card.append(text,button)}text.textContent=r.label+' · '+(r.phase==='ready'?(quotaPercent(r.snapshot.remainingFraction)+' · '+new Date(r.snapshot.queriedAt).toLocaleString(language)+(r.usable&&r.snapshot.remainingFraction===best?' · '+tr('recommend.best'):!r.usable?' · '+tr('recommend.stale'):'')):tr('recommend.'+r.phase));button.textContent=tr('recommend.choose');button.disabled=busy||!r.usable}el('compareAccounts').disabled=busy||choicesLoading||!el('model').value;el('cancelCompareAccounts').hidden=!s?.loading};
const renderQuota=q=>{quotaLoading=!!q?.loading;const row=q?.snapshot,date=value=>{const d=new Date(value);return Number.isNaN(d.valueOf())?tr("directImageView.4d8c1c5b42"):d.toLocaleString(language)};el('imageQuotaStatus').textContent=row?(typeof row.remainingFraction==='number'?tr("directImageView.486d6e6da9")+quotaPercent(row.remainingFraction):tr("directImageView.70cb67c0c4")):tr("directImageView.4712cf60be");el('quotaState').textContent=quotaLoading?tr("directImageView.d302f90b09")+(row?tr("directImageView.50de7101cd"):''):q?.error?tr("directImageView.bf4cedf76a")+(q.stale&&row?tr("directImageView.50de7101cd"):''):q?.stale?tr("directImageView.31043c91da"):row?tr("directImageView.434203a723"):'';el('imageQuotaReset').textContent=row?tr("directImageView.bce2a872e0")+(row.resetAt?date(row.resetAt):tr("directImageView.ecce09463f")):'';el('imageQuotaTime').textContent=row?tr("directImageView.d5f527cb73")+date(row.queriedAt):'';el('imageQuotaError').textContent=q?.error?q.error:''};
const renderReferences=s=>{referenceRevision=s.referenceRevision??0;referenceCount=s.references.length;el('referenceCount').textContent=referenceCount+' / 3';el('chooseReferences').textContent=referenceCount?tr("directImageView.dab9b32abe"):tr("directImageView.bc35022a3a");el('clearReferences').hidden=!referenceCount;el('references').hidden=!!referenceCount;el('referenceHelp').textContent=referenceCount?tr("directImageView.1c716813f5"):tr("directImageView.c303e09487");const list=el('referenceList');list.replaceChildren();const rows=s.referenceImages||s.references.map((name,index)=>({name,index}));for(const r of rows){const row=node('div','reference-item'),fallback=()=>node('span','reference-thumb reference-fallback',tr("directImageView.e8a1ec9934"));if(r.preview){const img=node('img','reference-thumb');img.src=r.preview;img.alt=r.name;img.onerror=()=>img.replaceWith(fallback());row.append(img)}else row.append(fallback());const text=node('div','reference-text');const name=node('p','reference-name',r.name);name.title=r.name;text.append(name);if(r.source)text.append(node('p','reference-source',tr("directImageView.448d7cbb9e")));row.append(text);const remove=node('button','quiet reference-remove',tr("directImageView.6135d4159e"));remove.type='button';remove.setAttribute('aria-label',tr("directImageView.c6ef2c0582")+r.name+tr("directImageView.aefce3a3a0"));remove.disabled=busy;remove.onclick=()=>send('removeReference',{index:r.index,revision:referenceRevision});row.append(remove);list.append(row)}};
const phases=()=>({confirming:tr("directImageView.a8b0bd9c65"),preparing:tr("directImageView.b53be09930"),generating:tr("directImageView.969ef41f7e"),validating:tr("directImageView.570d602067"),complete:tr("directImageView.f28461bb49"),partial:tr("directImageView.1bd16b45b4"),failed:tr("directImageView.6707de42c2"),cancelled:tr("directImageView.a37778f17c"),interrupted:tr("directImageView.88cf2dc00c")});
${imageResultScript}
const renderTasks=rows=>{const root=el('tasks');const keep=new Set(rows.map(t=>t.id));for(const child of [...root.children])if(!keep.has(child.dataset.id))child.remove();
 for(const [index,t] of rows.entries()){let card=[...root.children].find(c=>c.dataset.id===t.id);if(!card){card=node('article','task');card.dataset.id=t.id;root.prepend(card)}const expanded=card.querySelector('.task-details')?.open??local()['task:'+t.id]===true;card.replaceChildren();
 const heading=node('div','task-head');const time=new Date(t.createdAt);const phase=t.status?.includes('IMAGE_DIRECT_OUTCOME_UNKNOWN')?tr("directImageView.phaseUnknown"):phases()[t.phase]||t.phase;heading.append(node('span','task-label',tr("directImageView.59d96d3894")+String(index+1).padStart(2,'0')+' · '+(Number.isNaN(time.valueOf())?'':time.toLocaleTimeString(language, {hour:'2-digit',minute:'2-digit',second:'2-digit'}))),node('span','phase '+t.phase,phase));card.append(heading,...(t.accountLabel?[node('p','task-account task-params',tr("directImageView.af702badac")+t.accountLabel)]:[]),node('p','task-prompt',t.promptSummary),node('p','task-params',t.modelId+' · '+t.ratio+' · '+(t.size==='auto'?tr("directImageView.1686c16bcb"):t.size)+' · '+tr('directImageView.requestCount',{p0:t.count})),node('p','task-status',t.status));
 if(t.origin)card.append(node('p','lineage',tr("directImageView.f4c4893d14")+(t.origin.imageIndex+1)+tr("directImageView.1742b55b65")));
 const gallery=node('div','gallery');for(const image of t.images){const item=node('div','result-item');const button=node('button','image-result');button.type='button';button.disabled=busy;button.setAttribute('aria-label',tr("directImageView.69e192399e")+(index+1)+tr("directImageView.f842cb8dee")+(image.index+1));button.onclick=()=>send('preview',{taskId:t.id,index:image.index});if(image.preview&&!image.unavailable){const img=node('img');img.loading='lazy';img.decoding='async';img.src=image.preview;img.onerror=()=>{img.remove();button.append(node('span','',tr("directImageView.4d549987b4")))};img.alt=tr("directImageView.59d96d3894")+(index+1)+' · '+t.promptSummary;button.append(img)}button.append(node('span','', image.unavailable||tr("directImageView.81eab23665")+(image.index+1)+' · '+image.width+' × '+image.height));item.append(button);appendResultActions(item,t,image,index+1);gallery.append(item)}card.append(gallery);if(t.count>0){const reuse=node('button','result-action',tr('reuse.action'));reuse.disabled=busy;reuse.onclick=()=>send('reuseTask',{taskId:t.id});card.append(reuse)}
 const details=node('details','task-details');details.open=expanded;details.append(node('summary','',tr("directImageView.56b3909705")),node('p','task-id',tr("directImageView.02207d086a")+t.id),...(t.accountId?[node('p','task-id',tr("directImageView.50f2ddf46c")+t.accountId)]:[]),node('p','task-params',tr("directImageView.f86c2f4e8e")+t.createdAt+tr("directImageView.fcfb36cc5a")+t.quality));for(const image of t.images)details.append(node('p','task-id',image.name));details.addEventListener('toggle',()=>persist('task:'+t.id,details.open));const remove=node('button','secondary',tr("directImageView.f2cf9101bb"));remove.type='button';remove.disabled=busy;remove.setAttribute('aria-label',tr("directImageView.e94b6c765b")+(index+1)+tr("directImageView.a256ecc7d9"));remove.onclick=()=>api.postMessage({type:'deleteTask',taskId:t.id});details.append(remove);card.append(details);
 }el('taskCount').textContent=tr('directImageView.taskCount',{p0:rows.length});el('empty').hidden=rows.length>0;
};
let latestState;
const renderState=(s,preserveInput=false)=>{
 const incomingEpoch=s.draftEpoch??0,replacesDraft=incomingEpoch>draftEpoch;
 const staleDraft=incomingEpoch<draftEpoch||!replacesDraft&&(s.draftRevision??0)<draftRevision;
 if(replacesDraft){draftEpoch=incomingEpoch;draftRevision=s.draftRevision??0;}
 const input=!replacesDraft&&(preserveInput||staleDraft)?Object.fromEntries(['prompt','account','model','ratio','count','size','quality'].map(id=>[id,el(id).value])):undefined;
 if(s.actionRevision===undefined||s.actionRevision>=actionRevision)busy=!!s.busy;
 renderQuota(s.imageQuota);storageBlocked=!!s.storageBlocked;el('storageNotice').textContent=s.storageNotice||'';el('saveRecords').hidden=!storageBlocked;if(!staleDraft){accountBlocked=!!s.accountBlocked;choicesLoading=!!s.choicesLoading;accountRetryPending=!!s.accountRetryPending;}el('checkAccount').hidden=!s.canCheckAccount;el('checkAccount').textContent=tr("directImageView.c25fb86b1e");
 if(!staleDraft){options('account',[{id:'@current',label:tr("directImageView.2b6804ee08")},...s.choices.accounts]);const favorites=new Set(s.imageFavorites||[]);options('model',[...s.choices.models].sort((a,b)=>Number(favorites.has(b.id))-Number(favorites.has(a.id))).map(model=>({...model,label:(favorites.has(model.id)?'★ ':'')+model.label})));el('favoriteModel').textContent=tr(favorites.has(s.draft.modelId)?'quota.imageUnfavorite':'quota.imageFavorite');el('favoriteModel').setAttribute('aria-pressed',String(favorites.has(s.draft.modelId)));if(s.draft.modelId&&!s.choices.models.some(m=>m.id===s.draft.modelId)){const option=node('option','',s.draft.modelId+tr("directImageView.715be58bd9"));option.value=s.draft.modelId;option.disabled=true;el('model').append(option)}el('account').value=s.draft.followCurrent===false?s.draft.accountId:'@current';if(s.draft.modelId)el('model').value=s.draft.modelId;}
 for(const [id,key] of [['prompt','prompt'],['ratio','ratio'],['count','count'],['size','size'],['quality','quality']])if(replacesDraft||document.activeElement!==el(id))el(id).value=String(s.draft[key]);
 outputReady=!!s.outputDirectory;el('output').textContent=outputReady?tr("directImageView.46c3e2affe")+(s.outputName||s.outputDirectory.split(/[\\/]/).pop()):tr("directImageView.e777c8a2f6");renderReferences(s);el('status').textContent=s.status;el('accountStatus').textContent=s.accountStatus===tr("directImageView.fff0ffca40")?'':s.accountStatus||'';el('recentDiagnostic').textContent=s.recentDiagnostic;el('operationHistory').textContent=s.operationHistory||'';renderResultExtras(s);renderTasks(s.tasks||[]);
 if(input)for(const [id,value]of Object.entries(input))el(id).value=value;
 renderBusy();renderRecommendations(s.recommendation);
};
window.addEventListener('message',event=>{const s=event.data;if(s?.type==='language'){language=typeof s.language==='string'&&Object.hasOwn(dictionaries,s.language)?s.language:'zh-CN';applyLanguage();if(latestState)renderState(latestState,true);el('historyLabel').textContent=el('history').open?tr("directImageView.9d3b4f6443"):tr("directImageView.01baaf1f55");applyLayout();return;}if(s?.type==='state'){latestState=s;renderState(s,!!s.languageOnly)}});api.postMessage({type:'ready'});
</script></body></html>`;
}
