import { randomBytes } from 'node:crypto';
import { clientI18n, ht, locale } from './i18n';
export function quotaHistoryHtml(): string {
  const nonce = randomBytes(16).toString('hex'), label = (key: Parameters<typeof ht>[0]) => `<span data-i18n="${key}">${ht(key)}</span>`;
  return `<!doctype html><html lang="${locale()}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'"><style nonce="${nonce}">
  *{box-sizing:border-box}body{margin:0;padding:16px;color:var(--vscode-foreground);background:var(--vscode-editor-background);font:13px/1.5 var(--vscode-font-family);overflow-wrap:anywhere}main{max-width:950px;margin:auto;min-width:0}h1{font-size:19px}p{color:var(--vscode-descriptionForeground)}label{display:block}input,select,button{font:inherit;min-width:0;max-width:100%;padding:6px;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-widget-border)}select,input{width:100%}button{cursor:pointer;white-space:normal;overflow-wrap:anywhere}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--vscode-focusBorder)}.filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(180px,100%),1fr));gap:8px}.actions{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.panel{min-width:0;border:1px solid var(--vscode-widget-border);padding:10px;border-radius:6px;margin:12px 0}svg{width:100%;height:auto;display:block}svg text{fill:var(--vscode-descriptionForeground);font:11px sans-serif}.axis{stroke:var(--vscode-widget-border)}.point{fill:var(--vscode-charts-blue,#4aa5ff);cursor:pointer}.selected{fill:var(--vscode-charts-yellow,#ffba50)}.gap{stroke:var(--vscode-descriptionForeground);cursor:pointer}#point-detail{white-space:pre-wrap}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}td,th{text-align:left;padding:6px 3px;border-bottom:1px solid var(--vscode-widget-border);vertical-align:top;overflow-wrap:anywhere}summary{cursor:pointer}#notice{white-space:pre-wrap}
  </style></head><body><main><div class="actions"><button id="zh">简体中文</button><button id="en">English</button></div><h1>${label('history.title')}</h1><p>${label('history.hint')}</p><div class="filters"><div><label for="account-filter">${label('automation.account')}</label><select id="account-filter"></select></div><div><label for="kind-filter">${label('history.kind')}</label><select id="kind-filter"><option value="">${ht('history.all')}</option><option value="bucket">${ht('history.bucket')}</option><option value="image-model">${ht('history.image')}</option></select></div><div><label for="series-filter">${label('history.series')}</label><select id="series-filter"></select></div><div><label for="days-filter">${label('history.days')}</label><select id="days-filter"><option>1</option><option>7</option><option selected>30</option><option>90</option></select></div></div>
  <div class="panel"><p id="count" role="status"></p><svg id="chart" viewBox="0 0 700 290" role="img" aria-label="${ht('history.chart')}"></svg><label for="point-index">${label('history.point')}</label><input id="point-index" type="range" min="0" max="0" value="0"><p id="point-detail" aria-live="polite"></p></div><section class="panel"><h2>${label('history.detail')}</h2><div class="actions"><button id="prev">${label('history.prev')}</button><span id="page"></span><button id="next">${label('history.nextPage')}</button></div><table><thead><tr><th>${label('history.time')}</th><th>${label('automation.account')}</th><th>${label('history.series')}</th><th>${label('history.value')}</th></tr></thead><tbody id="rows"></tbody></table></section>
  <details class="panel"><summary>${label('history.manage')}</summary><label for="retention">${label('history.retention')}</label><input id="retention" type="number" min="1" max="90" value="30"><div class="actions"><button id="save-retention">${label('history.saveRetention')}</button><button id="clear-filter">${label('history.clearFilter')}</button><button id="clear-all">${label('history.clearAll')}</button></div></details><p id="notice" role="status"></p></main><script nonce="${nonce}">${clientI18n()}
  const api=acquireVsCodeApi(),$=id=>document.getElementById(id);let state={rows:[],accounts:[],now:Date.now()},shown=[],page=0,selected=0,restored=false,retentionDirty=false;const prior=api.getState()||{};
  for(const key of ['account-filter','kind-filter','series-filter','days-filter'])if(prior[key])$(key).value=prior[key];
  const send=(type,data={})=>api.postMessage({type,...data});const save=()=>api.setState(Object.fromEntries(['account-filter','kind-filter','series-filter','days-filter'].map(id=>[id,$(id).value])));
  const option=(text,value)=>new Option(text,value),series=r=>JSON.stringify([r.kind,r.key]);
  const date=t=>new Date(t).toLocaleString(language),reading=r=>r.status==='ready'?((r.fraction*100).toFixed(2)+'%'):tr('history.status.'+r.status),kind=r=>tr(r.kind==='bucket'?'history.bucket':'history.image');
  const details=r=>r.accountLabel+' · '+kind(r)+' · '+r.label+'\\n'+tr(r.observedAt?'history.observed':'history.failedAt',{p0:date(r.observedAt||r.eventAt)})+' · '+reading(r)+(r.resetAt?'\\n'+tr('quota.reset',{p0:date(r.resetAt)}):'');
  const sync=(id,choices)=>{const value=!restored&&prior[id]?prior[id]:$(id).value;$(id).replaceChildren(...choices.map(([label,key])=>option(label,key)));$(id).value=choices.some(x=>x[1]===value)?value:''};
  function render(){
    sync('account-filter',[[tr('history.all'),''],...state.accounts.map(a=>[a.label,a.id])]);const candidates=state.rows.filter(r=>(!$('account-filter').value||r.accountId===$('account-filter').value)&&(!$('kind-filter').value||r.kind===$('kind-filter').value));const keys=new Map(candidates.map(r=>[series(r),kind(r)+' · '+r.label]));sync('series-filter',[[tr('history.all'),''],...[...keys].map(([key,label])=>[label,key])]);
    shown=candidates.filter(r=>(!$('series-filter').value||series(r)===$('series-filter').value)&&Date.parse(r.eventAt)>=state.now-Number($('days-filter').value)*86400000);restored=true;$('count').textContent=tr('history.count',{p0:shown.length});page=Math.min(page,Math.max(0,Math.ceil(shown.length/100)-1));selected=Math.min(selected,Math.max(0,shown.length-1));$('point-index').max=Math.max(0,shown.length-1);$('point-index').value=selected;$('point-index').disabled=!shown.length;$('point-detail').textContent=shown.length?details(shown[selected]):tr('history.empty');
    const svg=$('chart');svg.replaceChildren();const node=(tag,attrs={},text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value]of Object.entries(attrs))n.setAttribute(key,String(value));if(text)n.textContent=text;svg.append(n);return n};
    for(const value of [0,25,50,75,100]){const y=245-value*2;node('line',{x1:44,x2:684,y1:y,y2:y,class:'axis'});node('text',{x:2,y:y+4},value+'%')}
    if(shown.length){const times=shown.map(r=>Date.parse(r.eventAt)),min=Math.min(...times),max=Math.max(...times),x=t=>44+(t-min)/Math.max(1,max-min)*640;node('text',{x:44,y:282},new Date(min).toLocaleDateString(language));node('text',{x:684,y:282,'text-anchor':'end'},new Date(max).toLocaleDateString(language));
    shown.forEach((r,i)=>{const p=r.status==='ready'?node('circle',{cx:x(times[i]),cy:245-r.fraction*200,r:i===selected?5:3,class:'point'+(i===selected?' selected':'')}):node('path',{d:'M '+(x(times[i])-3)+' 251 l 6 6 m -6 0 l 6 -6',class:'gap'});const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=details(r);p.append(title);p.onclick=()=>{selected=i;render()}})}
    $('rows').replaceChildren(...shown.slice().reverse().slice(page*100,(page+1)*100).map(r=>{const row=document.createElement('tr');for(const text of [date(r.observedAt||r.eventAt)+(r.observedAt?'':' · '+tr('history.status.failure')),r.accountLabel,kind(r)+' · '+r.label,reading(r)]){const td=document.createElement('td');td.textContent=text;row.append(td)}return row}));$('page').textContent=(page+1)+' / '+Math.max(1,Math.ceil(shown.length/100));$('prev').disabled=page===0;$('next').disabled=(page+1)*100>=shown.length;save();
  }
  for(const id of ['account-filter','kind-filter','series-filter','days-filter'])$(id).onchange=()=>{page=0;render()};$('point-index').oninput=()=>{selected=Number($('point-index').value);render()};$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};$('retention').oninput=()=>retentionDirty=true;$('save-retention').onclick=()=>{retentionDirty=false;send('retention',{days:Number($('retention').value)})};$('clear-filter').onclick=()=>send('clear',{ids:shown.map(r=>r.id)});$('clear-all').onclick=()=>send('clear',{all:true});$('zh').onclick=()=>send('language',{language:'zh-CN'});$('en').onclick=()=>send('language',{language:'en'});
  window.addEventListener('message',event=>{const m=event.data;if(m.type==='state'){state=m.state;if(!retentionDirty)$('retention').value=state.retentionDays;render()}if(m.type==='notice')$('notice').textContent=m.text;if(m.type==='language'){language=m.language;applyLanguage();$('kind-filter').options[0].textContent=tr('history.all');$('kind-filter').options[1].textContent=tr('history.bucket');$('kind-filter').options[2].textContent=tr('history.image');render()}});send('ready');
  </script></body></html>`;
}
